export const LOGIN_FORM_STORAGE_KEY = "LOGIN_FORM";
export const REGISTER_FORM_STORAGE_KEY = "REGISTER_FORM";
export const CREATE_IDEA_MODAL = "IDEA_MODAL";
export const CREATE_TOPIC_MODAL = "TOPIC_MODAL";
export const IDEA_COMMENT = "IDEA_COMMENT";
export const TOPIC_COMMENT = "TOPIC_COMMENT";
